In [1]:
#importing necessary libraries
import cvxpy as cp
import numpy as np

In [2]:
# initializing random 2x2 matrices A and B
np.random.seed(42) 
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)

In [3]:
# caculating the frobenius norm for A and B 
# frobenius norm of a matrix is the euclidean norm when it is viewed as a vector of its elements
norm_A = np.linalg.norm(A, 'fro')
norm_B = np.linalg.norm(B, 'fro')

In [4]:
# defining the ReLU activation function
def relu(x):
    return np.maximum(0, x)

In [5]:
# defining the variable x for the optimization problem
# it is a 2*1 matrice
X = cp.Variable((2, 1))

In [6]:
# defining the constraint: f(X) <= norm(A) * norm(B)
constraint = cp.norm(B @ cp.maximum(A @ X, 0), 2) <= norm_A * norm_B

In [7]:
# defining our objective which is to minimize f(X) given the constraints
objective = cp.Minimize(0)  

In [8]:
# defining the problem
problem = cp.Problem(objective, [constraint])

In [9]:
# solving the problem
problem.solve();

In [10]:
# getting the feasible solution
feasible_X = X.value if problem.status == cp.OPTIMAL else None

In [11]:
# printing the feasible solution
print(feasible_X)

[[-0.61171024]
 [ 0.13560253]]


In [12]:
def findx(A, B):    
    # caculating the frobenius norm for A and B 
    # Frobenius norm of a matrix is the Euclidean norm when it is viewed as a vector of its elements
    norm_A = np.linalg.norm(A, 'fro')
    norm_B = np.linalg.norm(B, 'fro')

    # defining the ReLU activation function
    def relu(x):
        return np.maximum(0, x)

    # defining the variable x for the optimization problem
    # it is a 2*1 matrice
    X = cp.Variable((2, 1))

    # defining the constraint: f(X) <= norm(A) * norm(B)
    constraint = cp.norm(B @ cp.maximum(A @ X, 0), 2) <= norm_A * norm_B

    # defining our objective which is to minimize f(X) given the constraints
    objective = cp.Minimize(0)  

    # defining the problem
    problem = cp.Problem(objective, [constraint])

    # solving the problem
    problem.solve();

    # getting the feasible solution
    feasible_X = X.value if problem.status == cp.OPTIMAL else None
    return feasible_X


In [13]:
# example 1
# A and B are 2*2 identity matrices
A= ([[1, 0],[0, 1]])
B= ([[1, 0],[0, 1]])
print(findx(A,B))

[[-0.16380744]
 [-0.16380744]]


C:\Users\Keya\anaconda3\lib\site-packages\cvxpy\expressions\constants\constant.py:53: UserWarning: Initializing a Constant with a nested list is undefined behavior. Consider using a numpy array instead.
  warnings.warn(NESTED_LIST_WARNING)


In [14]:
# example 2
A= ([[1, 1],[1, 1]])
B= ([[1, 1],[1, 1]])
print(findx(A,B))

[[-0.13663056]
 [-0.13663056]]


In [15]:
# example 3 
A= ([[1, 2],[2, 1]])
B= ([[1, 0],[0, 1]])
print(findx(A,B))

[[-0.14501157]
 [-0.14501157]]


In [16]:
# example 4 
A= ([[1, 2],[2, 1]])
B= ([[1, 2],[2, 1]])
print(findx(A,B))

[[-0.23875297]
 [-0.23875297]]


In [17]:
# example 5 
A= ([[2, 3],[3, 4]])
B= ([[6, 1],[2, 8]])
print(findx(A,B))

[[-0.51775871]
 [-0.0150125 ]]


In [18]:
# example 6 
A= ([[200, 300],[300, 400]])
B= ([[600, 100],[200, 800]])
print(findx(A,B))

[[  -0.80260322]
 [-216.79089754]]


In [19]:
# example 7
A= ([[18, 29],[36, 487]])
B= ([[12, 345],[890, 243]])
print(findx(A,B))

[[-597.84445796]
 [-116.80376786]]


In [20]:
# example 8
A= ([[-2, -3],[-3, -4]])
B= ([[-6, -1],[-2, -8]])
print(findx(A,B))

[[0.51775871]
 [0.0150125 ]]


In [21]:
# example 9
A= ([[20, 16],[90, 41]])
B= ([[65, 10],[22, 79]])
print(findx(A,B))

[[-8.21160356]
 [-7.182299  ]]


In [22]:
# example 10 
A= ([[3, 3],[3, 10]])
B= ([[6, 1],[2, 6]])
print(findx(A,B))

[[-0.28023744]
 [-0.23233844]]
